### ISSUE TITLE
Client doesnt work for some people.

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#510] opened 2017-02-04 14:01 UTC
The title says it, i just wanted to know if anyone had gotten anywhere with this problem.
in the console there is NO errors. So wtf can the problem be?
im sure its a problem on their side, but im loosing a lot of players because of this problem

**Comment by gyeyoqu** [comment] 2017-02-04 14:33
It's your server's problem ( XAMPP OR IIS) ?

**Comment by HAlexTM** [comment] 2017-02-04 14:34
Duplicate of #433

**Closed** 2017-02-04 14:35 UTC

**Comment by CalvinDKHD** [comment] 2017-02-04 15:23
uhh, i dont host it at home. I use VPSflame.com as a host.
What is the problem @gyeyoqu ??
Like can you explain so i can tell it to my host?

**Comment by Luka967** [comment] 2017-02-04 15:25
This is a client issue, not a server one xD
What does the console output?

**Comment by CalvinDKHD** [comment] 2017-02-04 15:27
Nothing, no error that i relevant to the issue.
![cbff52ed92aa0b4a83211abf79acbac6345fd67e39200dd3c3 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/18939977/22619545/cb91fbc8-eaf6-11e6-82ad-be8a05f32d83.jpg)

**Comment by CalvinDKHD** [comment] 2017-02-04 15:27
wait, sorry its bad quality. 1 sec.

**Comment by CalvinDKHD** [comment] 2017-02-04 15:28
The blocked my client ones is not it. ITs just adblock, it still happens if they completely delete adblock.

**Comment by Luka967** [comment] 2017-02-04 15:31
> `A Parser-blocking, cross-origin script, http://..., is invoked via document.write.`
I suspect this is the problem. Try using `script` tag inside html.

**Comment by CalvinDKHD** [comment] 2017-02-04 15:34
Well, that warning occurs for me too. And my site works just fine for me...
Here is my website - http://agarup.us/

**Comment by CalvinDKHD** [comment] 2017-02-04 15:35
And its just a ad btw.

**Comment by HAlexTM** [comment] 2017-02-04 15:37
You removed the repository link btw

**Comment by CalvinDKHD** [comment] 2017-02-04 15:37
sorry, what? lol
